name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Or your specific version
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./shop_app # <--- Add this line
        
      - name: Build APK
        run: flutter build apk --release
        working-directory: ./shop_app # <--- Add this line
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: shop_app/build/app/outputs/flutter-apk/app-release.apk # <--- Update path
